### ISSUE TITLE
nextcloud 16, aplication icon doesn't show up

### ISSUE THREAD

**Issue by robertsozolins** [nextcloud/files_photospheres#12]
Running nextcloud 16, aplication icon doesn't show up up in the Menubar.

**Comment by R0Wi** [comment]
Hi @robertsozolins ,

yes that's right, we decided to remove the icon in the current version, because we use an modal overlay to display the photospere images. In the old version this was slightly different, there we navigated to a new page an therefore needed the icon.

if you're ok with that, i would close this issue?

**Comment by robertsozolins** [comment]
go for it )
