### ISSUE TITLE
An error occurred trying to read xmp-data

### ISSUE THREAD

**Issue by kadrim** [nextcloud/files_photospheres#72]
recently my NC 21 does not work anymore for panoramas.

I get the exact same issue as reported here:

https://github.com/nextcloud/server/issues/25759

I will gladly assist in debugging this, if someone can tell me what else is needed to clarify

**Comment by kadrim** [comment]
clarification: sometimes it does work, sometimes not. i cannot yet determine why and when the issue happens.

**Comment by R0Wi** [comment]
Hi @kadrim, thanks for reporting this. Could you please post some snippets of your serverside and clientside logs? Could you also give some information regarding your setup?

**Comment by kadrim** [comment]
Thanks @R0Wi for your quick reply!

currently i cannot reproduce the issue. can it be related to some form of caching? i did rule out browser caching by using different browsers (always in-private-mode).

Or maybe it just happens with high io-load? my server (debian 10 VM on proxmox) was busy with backups today.

**Comment by R0Wi** [comment]
So the mentioned error message in the issue you provided (https://github.com/nextcloud/server/issues/25759) can only be thrown at
https://github.com/nextcloud/files_photospheres/blob/master/lib/Service/ShareService.php#L59. Are you dealing with shared files and/or folders? The message comes from NC core telling that the shared link does not exist anymore for whatever reason.

**Comment by kadrim** [comment]
in general yes, i use sharing. for the test i did perform yesterday, i just uploaded the file via the browser and tried to open it afterwards. so no sharing involved.

i also checked the NC logs, but nothing of relevance in there at the time of testing. maybe i would need more verbose output, but for that, the bug must be reproducible.


yesterday it happened 10 out of 9 attempts, but after my backup on the host-server finished (or some other coincidence) it worked again like a charm.

i even don't know if it is related to photosphere at all, i just reported it here, as this was suggested on the issue mentioned above.

what i will try next:

as my server is a VM, i will try to artifically limit the IOPS to see if this increases the chance to get the bug to reappear.

If you have any other suggestion, you are quite welcome :-)

**Comment by R0Wi** [comment]
Ok that sounds strange to my ears because i'm quite convinced that the error message can only be thrown at the point i mentioned. And that code is only executed if you access a file via a share link. But yes it seems like that if we have a look at the provided screenshots.

I'll provide a patch with extended logging, would be glad if you could check this one when it's finished. Also let me know your results regarding IO 👍

**Comment by kadrim** [comment]
will do, sir ;-)

**Comment by R0Wi** [comment]
@kadrim could you try the draft in #73 (maybe by patching via git `curl https://patch-diff.githubusercontent.com/raw/nextcloud/files_photospheres/pull/73.patch | git apply` while being inside the `nextlcloud/apps/files_photospheres` folder)? And please set the serverside [loglevel](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/logging_configuration.html#log-level) to `1` for the time debugging.

Then please post your log snippets here if that's possible. What's really strange ist that the error message really can just come from the point where the app tries to read XMP metadata for a shared file. So currently i cannot say why this is done when viewing a "regular" file when being logged in. So i think we will have to clarify this first because that's really strange.

**Comment by kadrim** [comment]
@R0Wi japp, will do. i am currently cloning my VM and will then enable the IOPS limiter to see if the bug will present itself again.

i tool the liberty to ask the original-bug-authors to participate aswell.

**Comment by lftsy** [comment]
Thanks @R0Wi , I tested your patch (on git clone version + git patch) and I do not have the error anymore (xmp-data error while clicking on picture in file details tab in file explorer) ! 
And photosphere is still working for me ! I will keep testing it and report you if I see another side effect and comparing with patch reverted

Thanks and Best Regards

**Comment by sylikc** [comment]
alright, i see this isn't an NC bug directly, and a photosphere bug.  Thanks for linking to this issue from the Server issue @kadrim .  So, the comment above about patching... **can I do this to a production instance without messing up the App upgradeability**?

I have now encountered it for 360 photos inside my NC 21 instance.

**Comment by R0Wi** [comment]
@sylikc thanks for the additional information. The patch can be applies without messing up the app if you're using the latest app version. It basically only adds some logging at various points so no need to be afraid here :-)

I'd really be looking forward if you could share your server logs after applying the steps in https://github.com/nextcloud/files_photospheres/issues/72#issuecomment-821974064.

One question: you're talking about sharing the **folder** which contains the photosphere image, not sharing the image directly, is this correct? Could be a important hint for me.

**Comment by sylikc** [comment]
@R0Wi yes, I had the error when viewing from the NC21 files when logged in.

Then I went to SHARE the FOLDER to see if someone else could see the photosphere (from the shared folder link), and it worked.

Then I went back to my logged in instance, and i could view the photosphere 360 with no errors.

**Comment by R0Wi** [comment]
Super strange 😄 Thank's for the hint, could help me for further investigation 👍

**Comment by sylikc** [comment]
ok, what I did now was unshare the folder... as soon as I unshare the folder, the error comes up again (and the 360 photo becomes flat again).

I'll run the patch and check server logs in a bit

**Comment by sylikc** [comment]
ok, so i ran the patch (had to remove the `.vscode/launch.json` stuff from the last commit... i need some help getting you the applicable logs

**Comment by sylikc** [comment]
odd... ok, so more information... currently the folder is NOT SHARED.  

1. I'm using latest Chrome on Windows 10 at the moment... 
2. I click a file, and it gives me that error (`An error occured while trying to read xmp-data: Share not found: The requested share does not exist anymore`)
3. I press `F5` to refresh and it gives me that error
4. I press `F5` to refresh and it gives me that error again
5. and sometimes when I mash F5, it loads it ... actually I can't reliably reproduce this behavior

**Comment by kadrim** [comment]
@sylikc i still suspect some kind of IO-Load to be responsible, but had no time yet to prepare my VM iwth an IOPS limit.

could you create some artificial IO on your NC-Server like copying large files while testing? And try to see if then the error is persistant?

otherway around: can you reduce the IO-Load on your system somehow and see if the error vanishes?

**Comment by sylikc** [comment]
@kadrim I'll try a large file sync test later .... but unfortunately my environment is kinda wonky.  

I'm running inside a virtual environment on relatively budget hardware... on top of that, the `data` folder is on an NFS share to a NAS.  Network is blazing fast though with LACP link on the virtual host.

I don't know how that would affect the way photospheres works, but my environment is probably not ideal to do IOPS limit testing, as there's lots more variables

**Comment by R0Wi** [comment]
Thank you all guys for sharing your information. @sylikc i can see in your logs that there is a request made to the endpoint which normally handles shared directories but this one shouldn't be triggered at all because you are in a "usual" login session which is handled differently under the hood. Currently i'm suspecting the javascript frontend function [here](https://github.com/nextcloud/files_photospheres/blob/4912d6698f9cb9e6940622a81c10dd3300a1fb84/js/fileAction.js#L422) which decides which endpoint to use for the current page, depending on whether it is a usual login session, a direcory share or a single file share (the latter two should only be used when accessing a share as an external user via share link). 

So the error seems to be that this function detects a directory share even though you're logged in and you do not have a share token on the current page. Since i cannot reproduce the issue on my NC21 instance i'd add some additional frontend logging and would kindly ask you, @sylikc and @kadrim , to patch again and share the browser logs?

**Comment by kadrim** [comment]
of course, will do as soon as you release the more verbose logging, i will apply it.

still struggling to reproduce the issue at all, and had no time yet to implement the iops limiter (will be doing that this weekend!)

**Comment by sylikc** [comment]
Browser logs? Like from inspecting? Need some quick tutorial on how lol

**Comment by R0Wi** [comment]
Thanks guys. @sylikc that's no problem, i'll inform you as soon as the new patch is available and help you to access the necessary logs 👍

**Comment by R0Wi** [comment]
I provided some additional logging output. Please try to patch again (see https://github.com/nextcloud/files_photospheres/issues/72#issuecomment-821974064) or use the artifact from https://github.com/nextcloud/files_photospheres/suites/2680011030/artifacts/59083216 .

For getting the browser logs please open the devtools via <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>I</kbd> (or right click -> inspect). Then change to the network tab on the top and make sure the `Disable cache` checkbox is checked.
![image](https://user-images.githubusercontent.com/19730957/117499327-5b263180-af7b-11eb-982f-473918f59f5a.png)

Then reload the page. Filter your console output to just show `Info`. You should be able to see log outputs like the ones shown below:
![image](https://user-images.githubusercontent.com/19730957/117499853-18b12480-af7c-11eb-8a07-344b72d7f025.png)


Please try to reproduce the error and share your browser logs if possible. Please let me know if you need further assistance.

**Comment by hobbsecky** [comment]
Hi. I have a fresh install of NextcloudVM. It's Nextcloud 21.0.1. I have had the same error with xmp-data. If I create a public link it worked with no issue. When logged in as the Nextcloud admin user I still got the error.

I did perform the patch you listed. I was going to send my output because initially it spit the same error message as admin. When I disabled the cache it worked perfectly. I cleared my browser cache (firefox) and have had no issues. I will do some additional testing with the unpatched app and making sure to clean my browser cache and I'll let you know what I find. Thanks!

**Comment by hobbsecky** [comment]
Removed Photosphere app, reinstalled, DID NOT PATCH, cleared Firefox browser cache. Have not seen the error message.

**Comment by sylikc** [comment]
I'm not exactly sure what's going on, but I went and did an inspect, and then did a disable cache... then it the XMP error happened twice....

then I refreshed a few times and I can no longer get it to trigger again (I had ran patched artifact, then even tried reverting it to the last patch)

It's pretty slow to load without cache though.

I can no longer get things to trigger the xmp error with the artifact attached in https://github.com/nextcloud/files_photospheres/issues/72#issuecomment-834723015

I think I saved this when there was an error... but doesn't look particularly interesting
<pre>
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 3.3.2
fileAction.js:431 isSharedViewer: false
fileAction.js:432 isDirectoryShare: false
fileAction.js:433 sharingToken:  undefined
fileAction.js:437 Init regular user view
session-heartbeat.js:97 session heartbeat polling started
VM9607 three.min.js:174 THREE.WebGLRenderer 93
</pre>

**Comment by Githopp192** [comment]
got the same error message with NC 21.0.1 - but i saw different outputs on different browsers:

- MS Edge - working fine (no errors at all on the same content !)
- Mozilla got the "An error occurred trying to read xmp-data" messages, too .. but only the first time 
  (when you forward/backward your pics, then the 2nd time .. no errors will be shown anymore).

i'm on Windows 10, all the Browers + Windows are on the newest versions.

**Comment by R0Wi** [comment]
@Githopp192 did you try to patch like stated https://github.com/nextcloud/files_photospheres/issues/72#issuecomment-821974064 ?

**Comment by R0Wi** [comment]
Should be fixed with `files_photospheres` `v1.21.1`. Thank you all for participating! Please feel free to reopen this issue if the problem is still present.

**Comment by lftsy** [comment]
Official app files_photospheres 1.21.1 reinstalled from app store and I am not able to reproduce the problem anymore / yet
Thank you very much for the fix !

Best Regards

**Comment by Githopp192** [comment]
yes, seems to be fixed. Thx for fixing.
