### ISSUE TITLE
How to use Markers? 

### ISSUE THREAD

**Issue by cloo** [nextcloud/files_photospheres#75]
There is a Markers button and Markers list panel in the app, but is totally unclear how they work. Is it somehow possible to add marker data in image file's XMP data? Or do you need to add an external file with markers data?

![210530-173217](https://user-images.githubusercontent.com/651760/120108423-b8be3000-c16d-11eb-8cd5-848d005314b5.png)

Could you add a line or two in the docs please?

**Comment by R0Wi** [comment]
HI @cloo , the markers feature is something embedded into the [`photo-sphere-viewer.js`](https://photo-sphere-viewer.js.org/) library and has to be activated by an additional plugin (https://photo-sphere-viewer.js.org/plugins/plugin-markers.html). Currently this is not supported by the app since markers data has to be stored and managed somewhere which might become quite a big new feature.

If you're really interessted in a feature like "adding and managing markers" we could discuss some usecases. But like i said this is nothing we can delivery in the near future so for the meantime i'll try to hide the markers button to prevent confusion.

**Comment by R0Wi** [comment]
Update: with the new version of `photo-sphere-viewer.js` (might be added in https://github.com/nextcloud/files_photospheres/issues/1) the markers button won't show until we explicitly enable the feature.

**Comment by cloo** [comment]
Thanks @R0Wi !

My use-case would have been simple. I use 360 panoramas for documenting spaces I later create designs for, and sometimes for documenting my designs in those spaces. And sometimes I share folders with panaoramas with my clients and coworkers.
Nextcloud is my main working platform, so opening pictures one-by-one is a little cumbersome, and at the same time I usually have to remember, which images were already viewed, and which not because thumbnails of panoramas are a often very similar. So if there was a way to navigate panoramas from within viewer, it would be very convenient. Could also be image list, not necessarily markers. Markers of course way cooler.
I understand this is a long shot, and possibly even not worth the effort. So just putting it out there so you know people like me exist.
