### ISSUE TITLE
Change configuration of Photo Sphere View

### ISSUE THREAD

**Issue by MarkusEder** [nextcloud/files_photospheres#83]
Hi, is ther a way to change config. Parameters of PSV as described here https://photo-sphere-viewer.js.org/guide/config.html#standard-options? I would like to increase the Zoomlevel minVow to 10.

**Comment by R0Wi** [comment]
Hi, currently the app is using Photo Sphere Viewer `v3`, so i'm not sure if this parameter already exists there and i did not find any docs for version 3 anymore. 

Unfortunately it's currently not possible to set any configuration because the app itself does not have any configuration UI nor any backend for that.

**Comment by MarkusEder** [comment]
THX, so I will wait for further vesions. Anyway it is a nice NC-plugin.
